services:
  vrising:
    container_name: v-rising
    image: mephi00/v-rising-wine:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: ./saves
        target: /saves
      - type: bind
        source: ./server
        target: /home/steam/Steam/steamapps/common/VRisingDedicatedServer
    environment:
      # https://github.com/StunlockStudios/vrising-dedicated-server-instructions/blob/master/1.1.x-pc/INSTRUCTIONS.md#autosavesmartkeep-and-autosavecount-settings
      - VR_NAME=WoWServer
      - VR_GAME_PORT=27015
      - VR_QUERY_PORT=27016
      - VR_ADDRESS=34.80.126.173
      - VR_HIDEIPADDRESS=false
      - VR_MAX_USERS=40
      - VR_MAX_ADMINS=4
      - VR_FPS=120
      - VR_LOWER_FPS_WHEN_EMPTY=true
      - VR_LOWER_FPS_WHEN_EMPTY_VALUE=5
      - VR_PASSWORD=363739
      - VR_SECURE=true
      - VR_LIST_ON_EOS=false
      - VR_LIST_ON_STEAM=true
      - VR_PRESET=StandardPvE
      - VR_DIFFICULTY_PRESET=Difficulty_Normal
      - VR_SAVE_NAME=WoW
      - VR_SAVE_COUNT=28
      - VR_SAVE_INTERVAL=43200
      - VR_LAN_MODE=false
      - VR_RESET_DAYS_INTERVAL=0

      - VR_RCON_ENABLED=true
      - VR_RCON_PORT=27020
      - VR_RCON_PASSWORD=363739
      - VR_RCON_BIND_ADDRESS=34.80.126.173
